### Find All Accounts

GET http://localhost:8080/atm/

### Create New Account

POST http://localhost:8080/atm/ HTTP/1.1 
content-type: application/json

{
"id" : 19, "owner" : "zwr", "balance" : 98
}

###
GET http://localhost:8080/atm/1/balance

###
DELETE http://localhost:8080/atm/18
